version: '2'
services:
    nsqlookupd:
        container_name: nsqlookupd
        image: nsqio/nsq
        restart: always
        ports:
            - 4160:4160
            - 4161:4161
        entrypoint: /nsqlookupd
        extra_hosts:
            - "mq.chideat.xyz:172.16.31.123"
    nsqadmin:
        container_name: nsqadmin
        image: nsqio/nsq
        restart: always
        ports:
            - 4170:4170
            - 4171:4171
        entrypoint: /nsqadmin --lookupd-http-address="mq.chideat.xyz:4161"
        extra_hosts:
            - "mq.chideat.xyz:172.16.31.123"
    nsqd:
        container_name: nsqd
        image: nsqio/nsq
        restart: always
        ports:
            - 4150:4150
            - 4151:4151
        entrypoint: /nsqd --broadcast-address="mq.chideat.xyz" --lookupd-tcp-address="mq.chideat.xyz:4160"
        extra_hosts:
            - "mq.chideat.xyz:172.16.31.123"
